### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by ghost** [BrahimJarrar/WIFI-Brute-Force#12]
[~] Cracking...                                                   
Traceback (most recent call last):                                 
  File "/home/kali/WifiBF/WifiBF.py", line 129, in <module>        
    menu()                                                         
  File "/home/kali/WifiBF/WifiBF.py", line 122, in menu            
    pwd(ssid, filee)                                               
  File "/home/kali/WifiBF/WifiBF.py", line 80, in pwd              
    main(ssid, pwd, number)                                        
  File "/home/kali/WifiBF/WifiBF.py", line 50, in main             
    profile = Profile()                                            
NameError: name 'Profile' is not defined

**Comment by DanielKaleby** [comment]
Where is the download?

**Comment by BernardoPiedade** [comment]
> [~] Cracking... Traceback (most recent call last): File "/home/kali/WifiBF/WifiBF.py", line 129, in menu() File "/home/kali/WifiBF/WifiBF.py", line 122, in menu pwd(ssid, filee) File "/home/kali/WifiBF/WifiBF.py", line 80, in pwd main(ssid, pwd, number) File "/home/kali/WifiBF/WifiBF.py", line 50, in main profile = Profile() NameError: name 'Profile' is not defined

Did you start the script as intended?
