### ISSUE TITLE
NameError: name 'iface' is not defined

### ISSUE THREAD

**Issue by VanshCodes** [BrahimJarrar/WIFI-Brute-Force#8]

**Comment by ghost** [comment]
pip install iface

**Comment by therealOri** [comment]
> -ghost "pip install iface"

`pip install iface` does nothing to fix this issue. (I am using manjaro linux and have confirmed to have iface pip installed.)


Error Log from my terminal Below. (This happens after typing in the wordlist and it starts cracking)
```
Traceback (most recent call last):
  File "WifiBF.py", line 129, in <module>
    menu()
  File "WifiBF.py", line 122, in menu
    pwd(ssid, filee)
  File "WifiBF.py", line 80, in pwd
    main(ssid, pwd, number)
  File "WifiBF.py", line 58, in main
    iface.remove_all_network_profiles()
NameError: name 'iface' is not defined
```

**Comment by hossainel** [comment]
I think you have a system error. And you saw a message like this first 

> [-] Error system

Reset your wifi router to get rid of the error
